In [1]:
import pandas as pd 
import numpy as np

In [2]:
# loading the data 

df = pd.read_csv("transactions.csv")

In [4]:
df.head(10)

,TransactionID,AccountID,TransactionAmount,TransactionDate,TransactionType,Location,DeviceID,IP Address,MerchantID,Channel,CustomerAge,CustomerOccupation,TransactionDuration,LoginAttempts,AccountBalance
0,TX000001,AC00128,14.09,04-11-2023 16:29,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21
1,TX000002,AC00455,376.24,6/27/2023 16:44,Debit,Houston,D000051,13.149.61.4,M052,ATM,68,Doctor,141,1,13758.91
2,TX000003,AC00019,126.29,07-10-2023 18:16,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35
3,TX000004,AC00070,184.50,05-05-2023 16:32,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06
4,TX000005,AC00411,13.45,10/16/2023 17:51,Credit,Atlanta,D000308,65.164.3.100,M091,Online,26,Student,198,1,7429.40
5,TX000006,AC00393,92.15,04-03-2023 17:15,Debit,Oklahoma City,D000579,117.67.192.211,M054,ATM,18,Student,172,1,781.68
6,TX000007,AC00199,7.08,2/15/2023 16:36,Credit,Seattle,D000241,140.212.253.222,M019,ATM,37,Doctor,139,1,13316.71
7,TX000008,AC00069,171.42,05-08-2023 17:47,Credit,Indianapolis,D000500,92.214.76.157,M020,Branch,67,Retired,291,1,2796.24
8,TX000009,AC00135,106.23,3/21/2023 16:59,Credit,Detroit,D000690,24.148.92.177,M035,Branch,51,Engineer,86,1,9095.14
9,TX000010,AC00385,815.96,3/31/2023 16:06,Debit,Nashville,D000199,32.169.88.41,M007,ATM,55,Doctor,120,1,1021.88

In [24]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2489 entries, 0 to 2488
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transactionid        2489 non-null   object
 1   accountid            2489 non-null   object
 2   transactionamount    2489 non-null   float64
 3   transactiondate      2489 non-null   datetime64[ns]
 4   transactiontype      2489 non-null   object
 5   location             2489 non-null   object
 6   deviceid             2489 non-null   object
 7   ip_address           2489 non-null   object
 8   merchantid           2489 non-null   object
 9   channel              2489 non-null   object
 10  customerage          2489 non-null   int64
 11  customeroccupation   2489 non-null   object
 12  transactionduration  2489 non-null   int64
 13  loginattempts        2489 non-null   int64
 14  accountbalance       2489 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(3), object(9)
memory usage: 291.8+ KB

transactionid          0
accountid              0
transactionamount      0
transactiondate        0
transactiontype        0
location               0
deviceid               0
ip_address             0
merchantid             0
channel                0
customerage            0
customeroccupation     0
transactionduration    0
loginattempts          0
accountbalance         0
dtype: int64

In [6]:
# fixing the column names 

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [7]:
df.columns

Index(['transactionid', 'accountid', 'transactionamount', 'transactiondate',
       'transactiontype', 'location', 'deviceid', 'ip_address', 'merchantid',
       'channel', 'customerage', 'customeroccupation', 'transactionduration',
       'loginattempts', 'accountbalance'],
      dtype='object')

In [9]:
# converting  date column
df['transactiondate'] = pd.to_datetime(df['transactiondate'], errors='coerce')

In [12]:
df['transactiondate'].head(10)

0   2023-04-11 16:29:00
1                   NaT
2   2023-07-10 18:16:00
3   2023-05-05 16:32:00
4                   NaT
5   2023-04-03 17:15:00
6                   NaT
7   2023-05-08 17:47:00
8                   NaT
9                   NaT
Name: transactiondate, dtype: datetime64[ns]

In [13]:
df['transactiondate'] = pd.to_datetime(
    df['transactiondate'],
    errors='coerce',
    dayfirst=True
)

In [14]:
df['transactiondate'].isnull().sum()

np.int64(47511)

In [15]:
df['transactiondate'].head(10)

0   2023-04-11 16:29:00
1                   NaT
2   2023-07-10 18:16:00
3   2023-05-05 16:32:00
4                   NaT
5   2023-04-03 17:15:00
6                   NaT
7   2023-05-08 17:47:00
8                   NaT
9                   NaT
Name: transactiondate, dtype: datetime64[ns]

In [16]:
def fix_date(x):
    try:
        return pd.to_datetime(x, dayfirst=True)
    except:
        try:
            return pd.to_datetime(x, dayfirst=False)
        except:
            return pd.NaT

df['transactiondate'] = df['transactiondate'].apply(fix_date)

In [17]:
df['transactiondate'].head(10)

0   2023-04-11 16:29:00
1                   NaT
2   2023-07-10 18:16:00
3   2023-05-05 16:32:00
4                   NaT
5   2023-04-03 17:15:00
6                   NaT
7   2023-05-08 17:47:00
8                   NaT
9                   NaT
Name: transactiondate, dtype: datetime64[ns]

In [18]:
df = df.dropna(subset=['transactiondate'])

In [19]:
df['transactiondate'].head(10)

0    2023-04-11 16:29:00
2    2023-07-10 18:16:00
3    2023-05-05 16:32:00
5    2023-04-03 17:15:00
7    2023-05-08 17:47:00
11   2023-02-06 17:30:00
12   2023-06-07 17:21:00
15   2023-12-12 16:23:00
19   2023-06-08 18:18:00
21   2023-08-11 18:31:00
Name: transactiondate, dtype: datetime64[ns]

In [20]:
df = df.reset_index(drop=True)

In [21]:
df.head(10)

,transactionid,accountid,transactionamount,transactiondate,transactiontype,location,deviceid,ip_address,merchantid,channel,customerage,customeroccupation,transactionduration,loginattempts,accountbalance
0,TX000001,AC00128,14.09,2023-04-11 16:29:00,Debit,San Diego,D000380,162.198.218.92,M015,ATM,70,Doctor,81,1,5112.21
1,TX000003,AC00019,126.29,2023-07-10 18:16:00,Debit,Mesa,D000235,215.97.143.157,M009,Online,19,Student,56,1,1122.35
2,TX000004,AC00070,184.50,2023-05-05 16:32:00,Debit,Raleigh,D000187,200.13.225.150,M002,Online,26,Student,25,1,8569.06
3,TX000006,AC00393,92.15,2023-04-03 17:15:00,Debit,Oklahoma City,D000579,117.67.192.211,M054,ATM,18,Student,172,1,781.68
4,TX000008,AC00069,171.42,2023-05-08 17:47:00,Credit,Indianapolis,D000500,92.214.76.157,M020,Branch,67,Retired,291,1,2796.24
5,TX000012,AC00459,190.02,2023-02-06 17:30:00,Debit,Memphis,D000589,116.175.11.222,M030,Online,21,Student,173,1,1528.81
6,TX000013,AC00392,494.52,2023-06-07 17:21:00,Credit,Mesa,D000032,210.98.198.143,M057,Branch,24,Student,111,1,1620.02
7,TX000016,AC00270,465.45,2023-12-12 16:23:00,Debit,Denver,D000466,221.169.49.152,M025,ATM,36,Engineer,129,1,3465.54
8,TX000020,AC00285,71.48,2023-06-08 18:18:00,Credit,Columbus,D000039,120.170.93.69,M039,Online,18,Student,169,1,6568.59
9,TX000022,AC00014,85.77,2023-08-11 18:31:00,Debit,Las Vegas,D000268,59.132.247.252,M065,Branch,38,Doctor,93,1,9146.19

In [22]:
df.shape

(2489, 15)

In [25]:
df['customerage'].dtype

dtype('int64')

In [26]:
df['customerage'].min(), df['customerage'].max()

(18, 80)

In [27]:
df['transactionamount'].dtype

dtype('float64')

In [28]:
df['transactionamount'].describe()

count    2489.000000
mean      290.900727
std       279.537275
min         0.250000
25%        81.510000
50%       213.980000
75%       398.520000
max      1905.990000
Name: transactionamount, dtype: float64

In [29]:
df['transactiontype'].dtype

dtype('O')

In [30]:
df['transactiontype'].unique()

array(['Debit', 'Credit'], dtype=object)

In [31]:
df['transactiontype'] = df['transactiontype'].str.lower().str.strip()
df['transactiontype'].unique()

array(['debit', 'credit'], dtype=object)

In [32]:
df['location'].dtype
df['location'].unique()[:10]

array(['San Diego', 'Mesa', 'Raleigh', 'Oklahoma City', 'Indianapolis',
       'Memphis', 'Denver', 'Columbus', 'Las Vegas', 'Atlanta'],
      dtype=object)

In [33]:
df['location'] = df['location'].str.strip().str.title()
df['location'].unique()[:10]

array(['San Diego', 'Mesa', 'Raleigh', 'Oklahoma City', 'Indianapolis',
       'Memphis', 'Denver', 'Columbus', 'Las Vegas', 'Atlanta'],
      dtype=object)

In [34]:
df['location'].nunique()

43

In [35]:
df['channel'].dtype
df['channel'].unique()

array(['ATM', 'Online', 'Branch'], dtype=object)

In [36]:
df['channel'] = df['channel'].str.lower().str.strip()
df['channel'].unique()

array(['atm', 'online', 'branch'], dtype=object)

In [37]:
df['loginattempts'].dtype
df['loginattempts'].describe()

count    2489.000000
mean        1.128566
std         0.615599
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         5.000000
Name: loginattempts, dtype: float64

In [38]:
df['loginattempts'] = df['loginattempts'].astype(int)

In [39]:
df['loginattempts'].dtype

dtype('int64')

In [40]:
# creating fraud flag
df['login_risk'] = df['loginattempts'] > 3

In [41]:
df['login_risk'].value_counts()

login_risk
False    2421
True       68
Name: count, dtype: int64

In [42]:
df[df['login_risk'] == True]

,transactionid,accountid,transactionamount,transactiondate,transactiontype,location,deviceid,ip_address,merchantid,channel,customerage,customeroccupation,transactionduration,loginattempts,accountbalance,login_risk
35,TX000092,AC00310,223.85,2023-10-02 16:36:00,debit,Kansas City,D000481,133.223.159.151,M009,atm,53,Engineer,55,4,2929.91,True
153,TX000401,AC00145,194.85,2023-09-12 16:50:00,debit,Jacksonville,D000601,148.234.210.167,M096,online,23,Student,130,4,319.84,True
201,TX000548,AC00456,97.09,2023-04-10 18:26:00,debit,Fort Worth,D000164,221.206.44.63,M052,atm,24,Student,202,4,1579.57,True
220,TX000595,AC00051,312.47,2023-05-02 17:24:00,debit,Milwaukee,D000658,207.157.126.125,M033,atm,49,Engineer,148,4,9419.27,True
224,TX000608,AC00150,32.54,2023-07-04 16:25:00,debit,Oklahoma City,D000008,4.101.189.38,M022,online,25,Student,183,4,1544.88,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2353,TX005917,AC00227,27.29,2022-05-09 00:00:00,debit,Los Angeles,D000101,114.223.129.47,M008,atm,57,Doctor,146,5,11197.54,True
2357,TX005924,AC00410,157.27,2025-12-02 00:00:00,credit,Los Angeles,D000255,110.150.1.201,M077,branch,27,Student,156,5,745.87,True
2391,TX006012,AC00465,109.05,2022-09-12 00:00:00,debit,Phoenix,D000673,48.89.167.189,M098,atm,56,Doctor,277,4,7487.79,True
2432,TX006127,AC00124,24.36,2024-07-04 00:00:00,debit,El Paso,D000079,74.58.165.67,M027,atm,46,Doctor,175,4,14851.28,True
2444,TX006160,AC00051,286.13,2023-08-12 00:00:00,debit,Milwaukee,D000658,207.157.126.125,M033,atm,49,Engineer,148,4,9419.27,True

In [43]:
#“I observed that most users had a single login attempt, but a small portion had multiple attempts (up to 5), 
#which is a strong fraud indicator. I created a login risk flag to identify such suspicious behavior.”

In [44]:
# transactionduration
df['transactionduration'].dtype
df['transactionduration'].describe()

count    2489.000000
mean      117.610687
std        69.349810
min        10.000000
25%        61.000000
50%       110.000000
75%       160.000000
max       300.000000
Name: transactionduration, dtype: float64

In [45]:
df['transactionduration'] = df['transactionduration'].astype(int)
df['transactionduration'].dtype

dtype('int64')

In [46]:
#Creating Duration Risk Flag
df['duration_risk'] = df['transactionduration'] > 180
df['duration_risk'].value_counts()

duration_risk
False    2125
True      364
Name: count, dtype: int64

In [47]:
df[df['duration_risk'] == True]

,transactionid,accountid,transactionamount,transactiondate,transactiontype,location,deviceid,ip_address,merchantid,channel,customerage,customeroccupation,transactionduration,loginattempts,accountbalance,login_risk,duration_risk
4,TX000008,AC00069,171.42,2023-05-08 17:47:00,credit,Indianapolis,D000500,92.214.76.157,M020,branch,67,Retired,291,1,2796.24,False,True
13,TX000032,AC00291,59.12,2023-02-06 16:24:00,debit,Baltimore,D000282,187.199.178.27,M053,atm,29,Doctor,257,1,9823.64,False,True
27,TX000063,AC00425,349.64,2023-11-07 16:48:00,debit,Las Vegas,D000516,9.230.41.239,M097,online,48,Engineer,226,1,6651.62,False,True
40,TX000105,AC00170,129.94,2023-01-02 16:36:00,debit,Las Vegas,D000647,111.226.226.202,M045,atm,32,Engineer,235,1,7954.92,False,True
43,TX000114,AC00121,213.76,2023-03-01 17:52:00,credit,Dallas,D000574,51.250.122.123,M009,atm,78,Retired,282,1,3528.72,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2468,TX006215,AC00116,5.22,2021-07-01 00:00:00,debit,Indianapolis,D000479,23.92.205.75,M062,online,52,Doctor,276,1,11263.89,False,True
2473,TX006222,AC00442,534.97,2025-02-05 00:00:00,debit,San Francisco,D000070,210.160.90.52,M009,branch,61,Doctor,265,1,12904.66,False,True
2476,TX006227,AC00177,308.08,2024-05-09 00:00:00,debit,Atlanta,D000515,188.205.152.176,M045,branch,49,Doctor,198,1,135.96,False,True
2485,TX006246,AC00421,236.00,2025-08-06 00:00:00,credit,San Antonio,D000451,26.105.49.129,M008,atm,18,Student,271,1,1328.73,False,True
2487,TX006249,AC00481,251.76,2022-04-11 00:00:00,debit,New York,D000617,49.10.93.200,M083,branch,76,Retired,246,1,4444.95,False,True

In [48]:
#I analyzed transaction duration and observed that unusually long durations could indicate suspicious behavior such as system delays or fraudulent attempts. 
#I created a duration-based risk flag to capture such anomalies.

In [49]:
df['fraud_flag'] = (
    (df['loginattempts'] > 3) |
    (df['transactionduration'] > 180) |
    (df['transactionamount'] > df['transactionamount'].quantile(0.95))
)

In [50]:
df['fraud_flag'].value_counts()

fraud_flag
False    1965
True      524
Name: count, dtype: int64

In [51]:
df[df['fraud_flag'] == True]

,transactionid,accountid,transactionamount,transactiondate,transactiontype,location,deviceid,ip_address,merchantid,channel,customerage,customeroccupation,transactionduration,loginattempts,accountbalance,login_risk,duration_risk,fraud_flag
4,TX000008,AC00069,171.42,2023-05-08 17:47:00,credit,Indianapolis,D000500,92.214.76.157,M020,branch,67,Retired,291,1,2796.24,False,True,True
13,TX000032,AC00291,59.12,2023-02-06 16:24:00,debit,Baltimore,D000282,187.199.178.27,M053,atm,29,Doctor,257,1,9823.64,False,True,True
27,TX000063,AC00425,349.64,2023-11-07 16:48:00,debit,Las Vegas,D000516,9.230.41.239,M097,online,48,Engineer,226,1,6651.62,False,True,True
31,TX000075,AC00265,1212.51,2023-10-04 16:36:00,debit,Indianapolis,D000231,193.83.0.183,M036,branch,20,Student,24,1,605.95,False,False,True
35,TX000092,AC00310,223.85,2023-10-02 16:36:00,debit,Kansas City,D000481,133.223.159.151,M009,atm,53,Engineer,55,4,2929.91,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,TX006222,AC00442,534.97,2025-02-05 00:00:00,debit,San Francisco,D000070,210.160.90.52,M009,branch,61,Doctor,265,1,12904.66,False,True,True
2476,TX006227,AC00177,308.08,2024-05-09 00:00:00,debit,Atlanta,D000515,188.205.152.176,M045,branch,49,Doctor,198,1,135.96,False,True,True
2480,TX006233,AC00028,1681.40,2023-11-01 00:00:00,debit,San Antonio,D000072,116.106.207.139,M064,branch,18,Student,65,1,1588.31,False,False,True
2485,TX006246,AC00421,236.00,2025-08-06 00:00:00,credit,San Antonio,D000451,26.105.49.129,M008,atm,18,Student,271,1,1328.73,False,True,True
2487,TX006249,AC00481,251.76,2022-04-11 00:00:00,debit,New York,D000617,49.10.93.200,M083,branch,76,Retired,246,1,4444.95,False,True,True

In [52]:
##I combined multiple behavioral indicators such as high transaction amount, multiple login attempts, and abnormal transaction duration to 
#create a composite fraud detection flag. This approach is more effective than relying on a single variable.

In [53]:
df.isnull().sum()

transactionid          0
accountid              0
transactionamount      0
transactiondate        0
transactiontype        0
location               0
deviceid               0
ip_address             0
merchantid             0
channel                0
customerage            0
customeroccupation     0
transactionduration    0
loginattempts          0
accountbalance         0
login_risk             0
duration_risk          0
fraud_flag             0
dtype: int64

In [54]:
df.duplicated().sum()

np.int64(0)

In [55]:
df['transactionid'].nunique(), len(df)

(2489, 2489)

In [56]:
df['accountbalance'].describe()

count     2489.000000
mean      5231.720783
std       3980.935434
min        101.250000
25%       1547.710000
50%       4875.860000
75%       7885.640000
max      14977.990000
Name: accountbalance, dtype: float64

In [57]:
df[df['accountbalance'] < 0]

Empty DataFrame
Columns: [transactionid, accountid, transactionamount, transactiondate, transactiontype, location, deviceid, ip_address, merchantid, channel, customerage, customeroccupation, transactionduration, loginattempts, accountbalance, login_risk, duration_risk, fraud_flag]
Index: []

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2489 entries, 0 to 2488
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   transactionid        2489 non-null   object
 1   accountid            2489 non-null   object
 2   transactionamount    2489 non-null   float64
 3   transactiondate      2489 non-null   datetime64[ns]
 4   transactiontype      2489 non-null   object
 5   location             2489 non-null   object
 6   deviceid             2489 non-null   object
 7   ip_address           2489 non-null   object
 8   merchantid           2489 non-null   object
 9   channel              2489 non-null   object
 10  customerage          2489 non-null   int64
 11  customeroccupation   2489 non-null   object
 12  transactionduration  2489 non-null   int64
 13  loginattempts        2489 non-null   int64
 14  accountbalance       2489 non-null   float64
 15  login_risk           2489 non-null   bool
 16  duration_risk        2489 non-null   bool
 17  fraud_flag           2489 non-null   bool
dtypes: bool(3), datetime64[ns](1), float64(2), int64(3), object(9)
memory usage: 299.1+ KB

In [59]:
df.to_csv("final_clean_transactions.csv", index=False)

In [61]:
#I performed end-to-end data cleaning and validation including handling missing values, standardizing categorical variables, validating numerical ranges, 
#ensuring data integrity, and creating behavioral fraud indicators such as login risk and duration risk.
#The final dataset was fully cleaned and ready for analysis and modeling.

In [62]:
df.to_csv("final_clean_transactions.csv", index=False)